name: Build WAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      # Optional: Upload the built WAR file as an artifact
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: food-hub-war
          path: target/*.war
